//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using SimpleJSON;


namespace cfg
{ 
   
public sealed partial class Tables
{
    public entity.TbEntityGroup TbEntityGroup {get; }
    public entity.TbEntity TbEntity {get; }
    public item.TbRecipe TbRecipe {get; }
    public item.TbItem TbItem {get; }
    public grid.TbTile TbTile {get; }
    public grid.TbUnit TbUnit {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbEntityGroup = new entity.TbEntityGroup(loader("entity_tbentitygroup")); 
        tables.Add("entity.TbEntityGroup", TbEntityGroup);
        TbEntity = new entity.TbEntity(loader("entity_tbentity")); 
        tables.Add("entity.TbEntity", TbEntity);
        TbRecipe = new item.TbRecipe(loader("item_tbrecipe")); 
        tables.Add("item.TbRecipe", TbRecipe);
        TbItem = new item.TbItem(loader("item_tbitem")); 
        tables.Add("item.TbItem", TbItem);
        TbTile = new grid.TbTile(loader("grid_tbtile")); 
        tables.Add("grid.TbTile", TbTile);
        TbUnit = new grid.TbUnit(loader("grid_tbunit")); 
        tables.Add("grid.TbUnit", TbUnit);
        PostInit();

        TbEntityGroup.Resolve(tables); 
        TbEntity.Resolve(tables); 
        TbRecipe.Resolve(tables); 
        TbItem.Resolve(tables); 
        TbTile.Resolve(tables); 
        TbUnit.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbEntityGroup.TranslateText(translator); 
        TbEntity.TranslateText(translator); 
        TbRecipe.TranslateText(translator); 
        TbItem.TranslateText(translator); 
        TbTile.TranslateText(translator); 
        TbUnit.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}