//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.entity
{ 

public sealed partial class EntityData :  Bright.Config.BeanBase 
{
    public EntityData(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  Name = _json["name"]; }
        { if(!_json["entity_group_id"].IsNumber) { throw new SerializationException(); }  EntityGroupId = (entity.EntityGroupId)_json["entity_group_id"].AsInt; }
        { if(!_json["asset_name"].IsString) { throw new SerializationException(); }  AssetName = _json["asset_name"]; }
        PostInit();
    }

    public EntityData(int id, string name, entity.EntityGroupId entity_group_id, string asset_name ) 
    {
        this.Id = id;
        this.Name = name;
        this.EntityGroupId = entity_group_id;
        this.AssetName = asset_name;
        PostInit();
    }

    public static EntityData DeserializeEntityData(JSONNode _json)
    {
        return new entity.EntityData(_json);
    }

    /// <summary>
    /// 实体id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 实体名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 实体组id
    /// </summary>
    public entity.EntityGroupId EntityGroupId { get; private set; }
    /// <summary>
    /// 实体资源名
    /// </summary>
    public string AssetName { get; private set; }

    public const int __ID__ = -1326876360;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "EntityGroupId:" + EntityGroupId + ","
        + "AssetName:" + AssetName + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
