//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.entity
{ 
    public enum EntityGroupId
    {
        /// <summary>
        /// 默认
        /// </summary>
        Default = 0,
        /// <summary>
        /// 地砖
        /// </summary>
        Tile = 1,
        /// <summary>
        /// 单位
        /// </summary>
        Unit = 2,
        /// <summary>
        /// 特效
        /// </summary>
        Effect = 3,
    }

} 
