//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.entity
{ 

public sealed partial class TbEntity
{
    private readonly Dictionary<int, entity.EntityData> _dataMap;
    private readonly List<entity.EntityData> _dataList;
    
    public TbEntity(JSONNode _json)
    {
        _dataMap = new Dictionary<int, entity.EntityData>();
        _dataList = new List<entity.EntityData>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = entity.EntityData.DeserializeEntityData(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, entity.EntityData> DataMap => _dataMap;
    public List<entity.EntityData> DataList => _dataList;

    public entity.EntityData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public entity.EntityData Get(int key) => _dataMap[key];
    public entity.EntityData this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}