//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.grid
{ 
    [System.Flags]
    public enum Direction
    {
        None = 0,
        /// <summary>
        /// X正方向
        /// </summary>
        Xp = 1,
        /// <summary>
        /// Y正方向
        /// </summary>
        Yp = 2,
        /// <summary>
        /// X负方向
        /// </summary>
        Xn = 4,
        /// <summary>
        /// Y负方向
        /// </summary>
        Yn = 8,
        /// <summary>
        /// X正负方向
        /// </summary>
        X = Xp|Xn,
        /// <summary>
        /// Y正负方向
        /// </summary>
        Y = Yp|Yn,
        /// <summary>
        /// 全向
        /// </summary>
        All = Xp|Xn|Yp|Yn,
    }

} 
