//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.grid
{ 
    public enum TileId
    {
        /// <summary>
        /// 没有什么特殊功能
        /// </summary>
        Ground = 10001,
        /// <summary>
        /// 什么也没有
        /// </summary>
        Empty = 10002,
        /// <summary>
        /// 只能在X方向往返
        /// </summary>
        ChannelX = 10003,
        /// <summary>
        /// 只能在Y方向往返
        /// </summary>
        ChannelY = 10004,
        /// <summary>
        /// 多移动一步
        /// </summary>
        Ice = 10005,
        /// <summary>
        /// 即刻定向移动玩家
        /// </summary>
        ConveyorBelt = 10006,
        /// <summary>
        /// 阻挡
        /// </summary>
        Wall = 10007,
    }

} 
