//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.grid
{ 
    public enum UnitId
    {
        None = 20000,
        /// <summary>
        /// 起点
        /// </summary>
        Start = 20001,
        /// <summary>
        /// 终点
        /// </summary>
        End = 20002,
        /// <summary>
        /// 灌木
        /// </summary>
        Bushes = 20003,
        /// <summary>
        /// 碎石
        /// </summary>
        Stone = 20004,
        /// <summary>
        /// 小树
        /// </summary>
        Tree = 20005,
        /// <summary>
        /// 大树
        /// </summary>
        BigTree = 20006,
        /// <summary>
        /// 树桩
        /// </summary>
        TreeStump = 20007,
        /// <summary>
        /// 巨石
        /// </summary>
        Rock = 20008,
        /// <summary>
        /// 苔石
        /// </summary>
        MossyRock = 20009,
        /// <summary>
        /// 矿石
        /// </summary>
        Ore = 20010,
        /// <summary>
        /// 大矿石
        /// </summary>
        BigOre = 20011,
        /// <summary>
        /// 水晶
        /// </summary>
        Crystal = 20012,
        /// <summary>
        /// 宝箱
        /// </summary>
        Treasure = 20013,
    }

} 
