//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.item
{ 
    public enum ItemId
    {
        None = 0,
        /// <summary>
        /// 树枝
        /// </summary>
        Branch = 1,
        /// <summary>
        /// 石头
        /// </summary>
        Stone = 2,
        /// <summary>
        /// 原木
        /// </summary>
        Log = 3,
        /// <summary>
        /// 铁
        /// </summary>
        Iron = 4,
        /// <summary>
        /// 水晶
        /// </summary>
        Crystal = 5,
        /// <summary>
        /// 木棒
        /// </summary>
        WoodBar = 6,
        /// <summary>
        /// 苹果
        /// </summary>
        Apple = 7,
        /// <summary>
        /// 水
        /// </summary>
        Water = 8,
        /// <summary>
        /// 石斧
        /// </summary>
        StoneAxe = 9,
        /// <summary>
        /// 石镐
        /// </summary>
        StonePickaxe = 10,
        /// <summary>
        /// 铁斧
        /// </summary>
        IronAxe = 11,
        /// <summary>
        /// 铁镐
        /// </summary>
        IronPickaxe = 12,
        /// <summary>
        /// 水晶斧
        /// </summary>
        CrystalAxe = 13,
        /// <summary>
        /// 水晶镐
        /// </summary>
        CrystalPickaxe = 14,
        /// <summary>
        /// 剪刀
        /// </summary>
        Scissors = 15,
        /// <summary>
        /// 铁剑
        /// </summary>
        IronSword = 16,
        /// <summary>
        /// 水晶剑
        /// </summary>
        CrystalSword = 17,
    }

} 
