//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.item
{ 

public abstract partial class Property :  Bright.Config.BeanBase 
{
    public Property(JSONNode _json) 
    {
        PostInit();
    }

    public Property() 
    {
        PostInit();
    }

    public static Property DeserializeProperty(JSONNode _json)
    {
        string type = _json["$type"];
        switch (type)
        {
            case "ToolProperty": return new item.ToolProperty(_json);
            case "FoodProperty": return new item.FoodProperty(_json);
            default: throw new SerializationException();
        }
    }



    public virtual void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public virtual void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
