//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.item
{ 
    [System.Flags]
    public enum ToolType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 斧
        /// </summary>
        Axe = 1,
        /// <summary>
        /// 镐
        /// </summary>
        Pickaxe = 2,
        /// <summary>
        /// 剑
        /// </summary>
        Sword = 3,
    }

} 
